### PR TITLE
Add windows compatibility

### PR DESCRIPTION
**Pull request by zwang20**

### CODE REVIEW

**Comment by edward-ji** [comment]
Usually, Mac uses the command and Windows uses the control modifier key (but not at the same time). Can we distinguish the two platforms and create two separate keymaps?

**Comment by zwang20** [comment]
> Usually, Mac uses the command and Windows uses the control modifier key (but not at the same time). Can we distinguish the two platforms and create two separate keymaps?

ok

**Comment by zwang20** [comment]
we should make this user configurable

**Comment by edward-ji** [comment]
> we should make this user configurable

But the default could be command on Mac and control on Windows as per convention. If we were to make it configurable, we as well build a complete shortcut settings tab. I just noticed that you created #20.

**Comment by edward-ji** [comment]
Although we could have updated the README to reflect this before merging, I feel like the README need a complete rework anyway.

**Pull request merged**
